[2022-11-18T00:03:47.249+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: cp_webcheck_failed_copy.http_check_copy scheduled__2022-11-17T00:00:00+00:00 [queued]>
[2022-11-18T00:03:47.266+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: cp_webcheck_failed_copy.http_check_copy scheduled__2022-11-17T00:00:00+00:00 [queued]>
[2022-11-18T00:03:47.269+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-18T00:03:47.280+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-18T00:03:47.282+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-18T00:03:47.308+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): http_check_copy> on 2022-11-17 00:00:00+00:00
[2022-11-18T00:03:47.317+0000] {standard_task_runner.py:55} INFO - Started process 1655 to run task
[2022-11-18T00:03:47.323+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'cp_webcheck_failed_copy', 'http_check_copy', 'scheduled__2022-11-17T00:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/cp_webcheck_failed copy.py', '--cfg-path', '/tmp/tmpex3a8q3b']
[2022-11-18T00:03:47.327+0000] {standard_task_runner.py:83} INFO - Job 24: Subtask http_check_copy
[2022-11-18T00:03:47.413+0000] {task_command.py:376} INFO - Running <TaskInstance: cp_webcheck_failed_copy.http_check_copy scheduled__2022-11-17T00:00:00+00:00 [running]> on host 5cf96c74ae22
[2022-11-18T00:03:47.535+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cp_webcheck_failed_copy
AIRFLOW_CTX_TASK_ID=http_check_copy
AIRFLOW_CTX_EXECUTION_DATE=2022-11-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-17T00:00:00+00:00
[2022-11-18T00:03:47.538+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-11-18T00:03:47.539+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl -s https://localhost > /dev/null']
[2022-11-18T00:03:47.567+0000] {subprocess.py:86} INFO - Output:
[2022-11-18T00:03:47.589+0000] {subprocess.py:97} INFO - Command exited with return code 7
[2022-11-18T00:03:47.609+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 7.
[2022-11-18T00:03:47.627+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=cp_webcheck_failed_copy, task_id=http_check_copy, execution_date=20221117T000000, start_date=20221118T000347, end_date=20221118T000347
[2022-11-18T00:03:47.660+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 24 for task http_check_copy (Bash command failed. The command returned a non-zero exit code 7.; 1655)
[2022-11-18T00:03:47.704+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-18T00:03:47.746+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
