[2022-11-21T01:03:50.470+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: cp_webcheck_failed.http_check scheduled__2022-11-20T00:00:00+00:00 [queued]>
[2022-11-21T01:03:50.500+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: cp_webcheck_failed.http_check scheduled__2022-11-20T00:00:00+00:00 [queued]>
[2022-11-21T01:03:50.502+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-21T01:03:50.503+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-21T01:03:50.505+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-21T01:03:50.528+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): http_check> on 2022-11-20 00:00:00+00:00
[2022-11-21T01:03:50.534+0000] {standard_task_runner.py:55} INFO - Started process 33720 to run task
[2022-11-21T01:03:50.546+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'cp_webcheck_failed', 'http_check', 'scheduled__2022-11-20T00:00:00+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/cp_webcheck_failed.py', '--cfg-path', '/tmp/tmptejs5cp3']
[2022-11-21T01:03:50.558+0000] {standard_task_runner.py:83} INFO - Job 67: Subtask http_check
[2022-11-21T01:03:50.660+0000] {task_command.py:376} INFO - Running <TaskInstance: cp_webcheck_failed.http_check scheduled__2022-11-20T00:00:00+00:00 [running]> on host 71a129efd3d8
[2022-11-21T01:03:50.754+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cp_webcheck_failed
AIRFLOW_CTX_TASK_ID=http_check
AIRFLOW_CTX_EXECUTION_DATE=2022-11-20T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-20T00:00:00+00:00
[2022-11-21T01:03:50.757+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-11-21T01:03:50.759+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl -s https://localhost > /dev/null']
[2022-11-21T01:03:50.794+0000] {subprocess.py:86} INFO - Output:
[2022-11-21T01:03:50.807+0000] {subprocess.py:97} INFO - Command exited with return code 7
[2022-11-21T01:03:50.823+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 7.
[2022-11-21T01:03:50.828+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=cp_webcheck_failed, task_id=http_check, execution_date=20221120T000000, start_date=20221121T010350, end_date=20221121T010350
[2022-11-21T01:03:50.847+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 67 for task http_check (Bash command failed. The command returned a non-zero exit code 7.; 33720)
[2022-11-21T01:03:50.875+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-21T01:03:50.896+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
