[2022-11-17T15:36:03.170+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: cp_webcheck_failed.http_check manual__2022-11-17T15:36:01.975572+00:00 [queued]>
[2022-11-17T15:36:03.177+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: cp_webcheck_failed.http_check manual__2022-11-17T15:36:01.975572+00:00 [queued]>
[2022-11-17T15:36:03.179+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-17T15:36:03.179+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-17T15:36:03.181+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-17T15:36:03.189+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): http_check> on 2022-11-17 15:36:01.975572+00:00
[2022-11-17T15:36:03.194+0000] {standard_task_runner.py:55} INFO - Started process 73 to run task
[2022-11-17T15:36:03.197+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'cp_webcheck_failed', 'http_check', 'manual__2022-11-17T15:36:01.975572+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/cp_webcheck_failed.py', '--cfg-path', '/tmp/tmp8yske3ta']
[2022-11-17T15:36:03.199+0000] {standard_task_runner.py:83} INFO - Job 15: Subtask http_check
[2022-11-17T15:36:03.241+0000] {task_command.py:376} INFO - Running <TaskInstance: cp_webcheck_failed.http_check manual__2022-11-17T15:36:01.975572+00:00 [running]> on host 5cf96c74ae22
[2022-11-17T15:36:03.283+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cp_webcheck_failed
AIRFLOW_CTX_TASK_ID=http_check
AIRFLOW_CTX_EXECUTION_DATE=2022-11-17T15:36:01.975572+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-17T15:36:01.975572+00:00
[2022-11-17T15:36:03.285+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-11-17T15:36:03.286+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl -s https://localhost > /dev/null']
[2022-11-17T15:36:03.296+0000] {subprocess.py:86} INFO - Output:
[2022-11-17T15:36:03.304+0000] {subprocess.py:97} INFO - Command exited with return code 7
[2022-11-17T15:36:03.312+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 7.
[2022-11-17T15:36:03.316+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=cp_webcheck_failed, task_id=http_check, execution_date=20221117T153601, start_date=20221117T153603, end_date=20221117T153603
[2022-11-17T15:36:03.326+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 15 for task http_check (Bash command failed. The command returned a non-zero exit code 7.; 73)
[2022-11-17T15:36:03.369+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-17T15:36:03.386+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
