[2022-12-01T00:10:36.926+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: cp_webcheck_failed_copy.http_check_copy scheduled__2022-11-30T00:00:00+00:00 [queued]>
[2022-12-01T00:10:36.968+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: cp_webcheck_failed_copy.http_check_copy scheduled__2022-11-30T00:00:00+00:00 [queued]>
[2022-12-01T00:10:36.972+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-01T00:10:36.973+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-12-01T00:10:36.975+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-01T00:10:37.040+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): http_check_copy> on 2022-11-30 00:00:00+00:00
[2022-12-01T00:10:37.057+0000] {standard_task_runner.py:55} INFO - Started process 4529 to run task
[2022-12-01T00:10:37.081+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'cp_webcheck_failed_copy', 'http_check_copy', 'scheduled__2022-11-30T00:00:00+00:00', '--job-id', '115', '--raw', '--subdir', 'DAGS_FOLDER/cp_webcheck_failed copy.py', '--cfg-path', '/tmp/tmpnd9fa__o']
[2022-12-01T00:10:37.093+0000] {standard_task_runner.py:83} INFO - Job 115: Subtask http_check_copy
[2022-12-01T00:10:37.260+0000] {task_command.py:376} INFO - Running <TaskInstance: cp_webcheck_failed_copy.http_check_copy scheduled__2022-11-30T00:00:00+00:00 [running]> on host 71a129efd3d8
[2022-12-01T00:10:37.455+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cp_webcheck_failed_copy
AIRFLOW_CTX_TASK_ID=http_check_copy
AIRFLOW_CTX_EXECUTION_DATE=2022-11-30T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-30T00:00:00+00:00
[2022-12-01T00:10:37.458+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-12-01T00:10:37.464+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl -s https://localhost > /dev/null']
[2022-12-01T00:10:37.530+0000] {subprocess.py:86} INFO - Output:
[2022-12-01T00:10:37.604+0000] {subprocess.py:97} INFO - Command exited with return code 7
[2022-12-01T00:10:37.627+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 7.
[2022-12-01T00:10:39.645+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=cp_webcheck_failed_copy, task_id=http_check_copy, execution_date=20221130T000000, start_date=20221201T001036, end_date=20221201T001039
[2022-12-01T00:10:39.706+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 115 for task http_check_copy (Bash command failed. The command returned a non-zero exit code 7.; 4529)
[2022-12-01T00:10:39.777+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-01T00:10:40.132+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
